version: "3"

services:
    app:
        container_name: app
        restart: always
        build: .
        ports:
            - "3000:3000"
        tty: true
        depends_on:
            - "mongo"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"